In [2]:
import numpy as np
import os
import sys
import pickle
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns
import re
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error
from scipy.stats import pearsonr, spearmanr
import shutil


In [42]:
def connect_dicts(dict1, dict2, save_path = None):
    merged_dict = {}
    for key in dict1.keys(): # 各keyごとに結合 
        merged_dict[key] = pd.concat([dict1[key], dict2[key]],
                                      axis=0, ignore_index=True)
        merged_dict = pd.DataFrame(merged_dict)
    if save_path: 
        with open(save_path, 'wb') as out_dir:
            pickle.dump(merged_dict, out_dir)
    return merged_dict

def connect_initial_sampling(random_list, rad_list, save = True):
    if type(random_list) != list:
        random_list = [random_list]
    if type(rad_list) != list:
        rad_list = [rad_list]
    for random in random_list:
        for rad in rad_list:
            for i in range(0, 4):
                with open(f'Random{random}_rad{rad}_to{i}.pkl', 'rb') as f1:
                    add_dict = pickle.load(f1)
                if i == 0:
                    ALL_dict = add_dict
                else:
                    ALL_dict = connect_dicts(ALL_dict, add_dict)
            if save:
                with open(f'Random{random}_rad{rad}_ALL.pkl', "wb") as f:
                    pickle.dump(ALL_dict, f)
    return ALL_dict

def check_dict(dict):
    for key, value in dict.items():
        print(f"Key: {key}, Type of value: {type(value)}, data_num: {value.shape}")

In [14]:
# エラーで止まった初期点と残りの初期点の結合
# random = 4
# rad = 0.5
# start = 2


# print(f'Random{random}_rad{rad}_to{start}')
# with open(f'Random{random}_rad{rad}_to{start}_sub.pkl', 'rb') as f1:
#                     dict1 = pickle.load(f1)
# with open(f'Random{random}_rad{rad}_to{start}.pkl', 'rb') as f2:
#                     dict2 = pickle.load(f2)
# connected_dict = connect_dicts(dict1, dict2)

# with open(f'Random{random}_rad{rad}_to{start}.pkl', 'wb') as f:
#         pickle.dump(connected_dict, f)

# check_dict(connected_dict)

Random4_rad0.5_to2
Key: x, Type of value: <class 'pandas.core.series.Series'>, data_num: (1000,)
Key: 50, Type of value: <class 'pandas.core.series.Series'>, data_num: (1000,)
Key: 100, Type of value: <class 'pandas.core.series.Series'>, data_num: (1000,)
Key: 150, Type of value: <class 'pandas.core.series.Series'>, data_num: (1000,)
Key: 200, Type of value: <class 'pandas.core.series.Series'>, data_num: (1000,)
Key: 250, Type of value: <class 'pandas.core.series.Series'>, data_num: (1000,)
Key: 300, Type of value: <class 'pandas.core.series.Series'>, data_num: (1000,)
Key: 350, Type of value: <class 'pandas.core.series.Series'>, data_num: (1000,)


In [51]:
random_list = list(range(1,7))
print(random_list)

[1, 2, 3, 4, 5, 6]


In [53]:
random_list = list(range(2,7))
rad_list = [0.5, 0.75]
# type(rad_list)
connect_initial_sampling(random_list, rad_list, save = True)


x  \
0     [0.03981642902361405, 0.018235784500910925, 0....   
1     [0.07715431978463508, 0.02829473905300412, 0.0...   
2     [0.08703336754800317, 0.09791217049075601, 0.0...   
3     [0.06351647893859516, 0.08283973725347911, 0.0...   
4     [0.01488947578227349, 0.07805357302725335, 0.0...   
...                                                 ...   
3995  [0.036732511659635536, 0.0032912351589887245, ...   
3996  [0.09460992917822181, 0.0337240049309328, 0.03...   
3997  [0.06681162122195673, 0.01732945868029274, 0.0...   
3998  [0.007918910062253091, 0.08387741161914945, 0....   
3999  [0.06336138655905248, 0.08507229299027341, 0.0...   

                                                     50  \
0     {'compliance': [[-0.0647757]], 'stress': [[-0....   
1     {'compliance': [[-0.0673742]], 'stress': [[-1....   
2     {'compliance': [[-0.0640686]], 'stress': [[-0....   
3     {'compliance': [[-0.068174]], 'stress': [[-1.0...   
4     {'compliance': [[-0.0650937]], 'stress': [[-0....   
...                                                 ...   
3995  {'compliance': [[-0.0582825]], 'stress': [[-0....   
3996  {'compliance': [[-0.0656805]], 'stress': [[-0....   
3997  {'compliance': [[-0.0629887]], 'stress': [[-0....   
3998  {'compliance': [[-0.0585949]], 'stress': [[-1....   
3999  {'compliance': [[-0.0642102]], 'stress': [[-0....   

                                                    100  \
0     {'compliance': [[-0.0888197]], 'stress': [[-1....   
1     {'compliance': [[-0.082365]], 'stress': [[-1.8...   
2     {'compliance': [[-0.0980222]], 'stress': [[-1....   
3     {'compliance': [[-0.0996179]], 'stress': [[-2....   
4     {'compliance': [[-0.0789836]], 'stress': [[-1....   
...                                                 ...   
3995  {'compliance': [[-0.0798525]], 'stress': [[-1....   
3996  {'compliance': [[-0.085654]], 'stress': [[-1.6...   
3997  {'compliance': [[-0.070355]], 'stress': [[-1.5...   
3998  {'compliance': [[-0.105179]], 'stress': [[-1.1...   
3999  {'compliance': [[-0.100039]], 'stress': [[-0.8...   

                                                    150  \
0     {'compliance': [[-0.118551]], 'stress': [[-2.1...   
1     {'compliance': [[-0.1115]], 'stress': [[-2.314...   
2     {'compliance': [[-0.149684]], 'stress': [[-3.3...   
3     {'compliance': [[-0.1325]], 'stress': [[-2.961...   
4     {'compliance': [[-0.108039]], 'stress': [[-3.7...   
...                                                 ...   
3995  {'compliance': [[-0.104739]], 'stress': [[-3.9...   
3996  {'compliance': [[-0.103676]], 'stress': [[-2.3...   
3997  {'compliance': [[-0.158186]], 'stress': [[-1.5...   
3998  {'compliance': [[-0.121391]], 'stress': [[-2.8...   
3999  {'compliance': [[-0.126642]], 'stress': [[-2.9...   

                                                    200  \
0     {'compliance': [[-0.142345]], 'stress': [[-2.5...   
1     {'compliance': [[-0.134424]], 'stress': [[-2.7...   
2     {'compliance': [[-0.168417]], 'stress': [[-2.8...   
3     {'compliance': [[-0.144511]], 'stress': [[-2.0...   
4     {'compliance': [[-0.125477]], 'stress': [[-1.6...   
...                                                 ...   
3995  {'compliance': [[-0.112104]], 'stress': [[-3.5...   
3996  {'compliance': [[-0.119546]], 'stress': [[-3.6...   
3997  {'compliance': [[-0.206386]], 'stress': [[-1.7...   
3998  {'compliance': [[-0.129222]], 'stress': [[-1.3...   
3999  {'compliance': [[-0.163762]], 'stress': [[-5.1...   

                                                    250  \
0     {'compliance': [[-0.151424]], 'stress': [[-3.4...   
1     {'compliance': [[-0.15021]], 'stress': [[-3.57...   
2     {'compliance': [[-0.165036]], 'stress': [[-4.0...   
3     {'compliance': [[-0.152559]], 'stress': [[-2.2...   
4     {'compliance': [[-0.140541]], 'stress': [[-2.1...   
...                                                 ...   
3995  {'compliance': [[-0.119043]], 'stress': [[-2.5...   
3996  {'compliance': [[-0.124284]], '

In [55]:
# 初期点の選び方
random_num = 2
rad = 0.5
mesh = 50
path = f"Random{random_num}_rad{rad}_ALL.pkl"
with open(path, "rb") as f:
    data = pickle.load(f)

data_x = np.vstack(data["x"])
data_co = data[f"{mesh}"].apply(lambda x:x["compliance"].item())
data_st = data[f"{mesh}"].apply(lambda x:x["stress"].item())
data_cost = data[f"{mesh}"].apply(lambda x:x["cost"])

print(np.array(data_x))
print(np.array(data_co[0:3]).reshape(-1, 1))
print(np.array(data_st[0:3]).reshape(-1, 1))
print(np.array(data_cost[0:3]))


[[0.09447154 0.03117606 0.06164064 ... 0.08958888 0.01719014 0.05070788]
 [0.0663493  0.0007765  0.00777209 ... 0.02461066 0.06190318 0.0915361 ]
 [0.0867484  0.09356819 0.00311907 ... 0.09155183 0.06910918 0.00526425]
 ...
 [0.06681162 0.01732946 0.07235901 ... 0.0213953  0.05082716 0.02907656]
 [0.02043953 0.06210875 0.09783277 ... 0.07875687 0.04106949 0.00969502]
 [0.00791891 0.08387741 0.00923104 ... 0.01212453 0.03390806 0.01158279]]
[[-0.0666761]
 [-0.0633016]
 [-0.0756596]]
[[-0.588903]
 [-0.499402]
 [-1.02037 ]]
[31.6539 31.0117 30.8309]


In [3]:
# データの読み込み, 加工
for start in [0]:
    data_frame_co = {}
    data_frame_st = {}
    data_frame_cost = {}
    for random_num in range(2,7):
        for rad in [0.5, 0.75]:
            # if rad == 0.5 and random_num == 3:
            #     pass
            # else:
            path = f"Random{random_num}_rad{rad}_ALL.pkl"
            with open(path, "rb") as f:
                data = pickle.load(f)
            print("==========================")
            print(f"Random{random_num}_rad{rad}_start{start}", data.shape)
            # data.info()
            # pg = sns.pairplot(data)
            for mesh in reversed([50*i for i in range(1,8)]):
                mesh_data = data[f'{mesh}']

                data_co = mesh_data.apply(lambda x:x["compliance"].item())
                data_st = mesh_data.apply(lambda x:x["stress"].item())
                data_cost = mesh_data.apply(lambda x:x["cost"])

                mean_co = data_co.mean()
                mean_st = data_st.mean()
                mean_cost = data_cost.mean()

                std_co = data_co.std()
                std_st = data_st.std()
                std_cost = data_cost.std()
                
                data_frame_co[f"Random{random_num}_rad{rad}_mesh{mesh}_compliance"] = -data_co
                data_frame_st[f"Random{random_num}_rad{rad}_mesh{mesh}_stress"] = -data_st
                data_frame_cost[f"Random{random_num}_rad{rad}_mesh{mesh}_cost"] = data_cost

                if len(mesh_data) != 4000: 
                    print("----------------------------")
                    print(f"Mesh: {mesh}")
                    print("data_num=", len(mesh_data))
                    
                
                    for data_obj, mean_obj, std_obj, obj_name in zip([data_co, data_st], [mean_co, mean_st], [std_co, std_st] ,["compliance", "stress"]):
                        if mesh == 350:
                            if obj_name == "compliance":
                                x_co = -data_obj.values.reshape(-1, 1)
                            elif obj_name == "stress":
                                x_st = -data_obj.values.reshape(-1, 1)
                        x = x_co if obj_name == "compliance" else x_st
                        y = -data_obj.values.reshape(-1, 1)

                        # print("mesh=350 の index 一部:", x.flatten()[:10])
                        # print("mesh=50 の index 一部:", y.flatten()[:10])

                        # NaN が含まれているインデックス（True の位置）を取得
                        nan_indices_x = np.where(np.isnan(x))[0]
                        nan_indices_y = np.where(np.isnan(y))[0]

                        print(f"Random{random_num}_rad{rad} Mesh: {mesh}")
                        # print("x に NaN があるインデックス:", nan_indices_x)
                        # print("y に NaN があるインデックス:", nan_indices_y)
                        if len(nan_indices_x) == 0:
                            # # 二乗誤差
                            mse = mean_squared_error(x, y)

                            # ピアソン相関（線形の強さ）
                            pearson_corr, _ = pearsonr(x.flatten(), y.flatten())

                            # スピアマン相関（順位の一致）
                            spearman_corr, _ = spearmanr(x.flatten(), y.flatten())

                            # print(f"Mean {obj_name}: {-mean_obj:.4f} ± {std_obj:.4f}")
                            # print(f"📊 ピアソン相関係数: {pearson_corr:.4f}")
                            # print(f"📈 スピアマン相関係数: {spearman_corr:.4f}")
                            # print(f"{obj_name}二乗誤差{mesh}: {mse:.6f}")

                    print(f"Mean Cost: {mean_cost:.4f} ± {std_cost:.4f}")



            

Random2_rad0.5_start0 (4000, 8)
Random2_rad0.75_start0 (4000, 8)
Random3_rad0.5_start0 (4000, 8)
Random3_rad0.75_start0 (4000, 8)
Random4_rad0.5_start0 (4000, 8)
Random4_rad0.75_start0 (4000, 8)
Random5_rad0.5_start0 (4000, 8)
Random5_rad0.75_start0 (4000, 8)
Random6_rad0.5_start0 (4000, 8)
Random6_rad0.75_start0 (4000, 8)


In [4]:
for data_frame_obj, obj_name in zip([data_frame_co, data_frame_st], ["compliance", "stress"]):
    for random_num in range(2,6):
        for rad in [0.5, 0.75]:
            data_frame = pd.DataFrame(data_frame_obj)
            columns = [col for col in data_frame.columns if f"Random{random_num}_rad{rad}" in col]
            data = data_frame[columns]

            x = data[f"Random{random_num}_rad{rad}_mesh350_{obj_name}"].values.reshape(-1, 1)

            for mesh in [50*i for i in range(1,8)]:
                y = data[f"Random{random_num}_rad{rad}_mesh{mesh}_{obj_name}"].values.reshape(-1, 1)
                print(y[:5])


                # NaN が含まれているインデックス（True の位置）を取得
                nan_indices_x = np.where(np.isnan(x))[0]
                nan_indices_y = np.where(np.isnan(y))[0]

                print("----------------------------")
                print(f"Random{random_num}_rad{rad} Mesh: {mesh}")
                # print("x に NaN があるインデックス:", nan_indices_x)
                # print("y に NaN があるインデックス:", nan_indices_y)
                if len(nan_indices_x) == 0:

                    # # 二乗誤差
                    mse = mean_squared_error(x, y)

                    # ピアソン相関（線形の強さ）
                    pearson_corr, _ = pearsonr(x.flatten(), y.flatten())

                    # スピアマン相関（順位の一致）
                    spearman_corr, _ = spearmanr(x.flatten(), y.flatten())

                    print(f"📊 ピアソン相関係数: {pearson_corr:.4f}")
                    print(f"📈 スピアマン相関係数: {spearman_corr:.4f}")

                    print(f"{obj_name}二乗誤差{mesh}: {mse:.6f}")


[[0.0666761]
 [0.0633016]
 [0.0756596]
 [0.063024 ]
 [0.0622364]]
----------------------------
Random2_rad0.5 Mesh: 50
📊 ピアソン相関係数: -0.0253
📈 スピアマン相関係数: 0.0325
compliance二乗誤差50: 0.009336
[[0.0750143]
 [0.0758216]
 [0.0776986]
 [0.0879166]
 [0.0704414]]
----------------------------
Random2_rad0.5 Mesh: 100
📊 ピアソン相関係数: 0.0505
📈 スピアマン相関係数: 0.0351
compliance二乗誤差100: 0.006311
[[0.109951]
 [0.100075]
 [0.10737 ]
 [0.100402]
 [0.121508]]
----------------------------
Random2_rad0.5 Mesh: 150
📊 ピアソン相関係数: 0.6083
📈 スピアマン相関係数: 0.6143
compliance二乗誤差150: 0.002936
[[0.133025]
 [0.114686]
 [0.139996]
 [0.112031]
 [0.133415]]
----------------------------
Random2_rad0.5 Mesh: 200
📊 ピアソン相関係数: 0.8791
📈 スピアマン相関係数: 0.8874
compliance二乗誤差200: 0.000914
[[0.131305]
 [0.120555]
 [0.131276]
 [0.11769 ]
 [0.136304]]
----------------------------
Random2_rad0.5 Mesh: 250
📊 ピアソン相関係数: 0.9411
📈 スピアマン相関係数: 0.9402
compliance二乗誤差250: 0.000544
[[0.144528]
 [0.133448]
 [0.149738]
 [0.127555]
 [0.154443]]
--------------------

In [ ]:
# compliance 比較グラフ
os.makedirs("Result_graph", exist_ok=True)
for random_num in range(2,7):
    for rad in [0.5, 0.75]:
        data_frame = pd.DataFrame(data_frame_co)
        columns = [col for col in data_frame.columns if f"Random{random_num}_rad{rad}" in col][::-1]
        g = sns.pairplot(data_frame[columns], kind="reg", plot_kws={"line_kws": {"color": "red"}})

        g.figure.suptitle(f"Random{random_num}_rad{rad}_compliance", fontsize=40)
        g.figure.subplots_adjust(top=0.95)

        min350 = data_frame[f"Random{random_num}_rad{rad}_mesh350_compliance"].min()
        max350 = data_frame[f"Random{random_num}_rad{rad}_mesh350_compliance"].max()

        # 全体のプロット（g）に対して、対角以外に同じ軸範囲で y = x を描画
        for i in range(g.axes.shape[0]):
            for j in range(g.axes.shape[1]):
                if i != j:
                    ax = g.axes[i, j]
                    # ax.set_xlim(min350, max350)
                    # ax.set_ylim(min350, max350)
                    ax.set_xlim(min350*0.7, max350*1.0)
                    ax.set_ylim(min350*0.7, max350*1.0)

                    ax.plot([min350, max350], [min350, max350], color='red', linestyle='--')
        for i, col in enumerate(columns):
            label = re.sub(f"Random{random_num}_rad{rad}_", "", col).replace("_compliance", "")
            g.axes[i, 0].set_ylabel(label, fontsize=14)
            g.axes[-1, i].set_xlabel(label, fontsize=14)

        plt.savefig(f"Result_graph/Random{random_num}_rad{rad}_compliance.pdf", bbox_inches='tight')
        plt.close()

In [6]:
# stress 比較グラフ
os.makedirs("Result_graph", exist_ok=True)
for random_num in range(2,7):
    for rad in [0.5, 0.75]:
        data_frame = pd.DataFrame(data_frame_st)
        columns = [col for col in data_frame.columns if f"Random{random_num}_rad{rad}" in col][::-1]
        g = sns.pairplot(data_frame[columns], kind="reg", plot_kws={"line_kws": {"color": "red"}})

        g.figure.suptitle(f"Random{random_num}_rad{rad}_stress", fontsize=40)
        g.figure.subplots_adjust(top=0.95)

        min350 = data_frame[f"Random{random_num}_rad{rad}_mesh350_stress"].min()
        max350 = data_frame[f"Random{random_num}_rad{rad}_mesh350_stress"].max()

        # 全体のプロット（g）に対して、対角以外に同じ軸範囲で y = x を描画
        for i in range(g.axes.shape[0]):
            for j in range(g.axes.shape[1]):
                if i != j:
                    ax = g.axes[i, j]
                    # ax.set_xlim(min350, max350)
                    # ax.set_ylim(min350, max350)
                    ax.set_xlim(min350*0.9, max350*1.1)
                    ax.set_ylim(min350*0.9, max350*1.1)

                    ax.plot([min350, max350], [min350, max350], color='red', linestyle='--')
        for i, col in enumerate(columns):
            label = re.sub(f"Random{random_num}_rad{rad}_", "", col).replace("_stress", "")
            g.axes[i, 0].set_ylabel(label, fontsize=14)
            g.axes[-1, i].set_xlabel(label, fontsize=14)

        plt.savefig(f"Result_graph/Random{random_num}_rad{rad}_stress.pdf", bbox_inches='tight')
        plt.close()

In [ ]:
# cost 比較グラフ
os.makedirs("Result_graph", exist_ok=True)
for random_num in range(2,7):
    for rad in [0.5, 0.75]:
        data_frame = pd.DataFrame(data_frame_cost)
        columns = [col for col in data_frame.columns if f"Random{random_num}_rad{rad}" in col][::-1]
        g = sns.pairplot(data_frame[columns], kind="reg", plot_kws={"line_kws": {"color": "red"}})

        g.figure.suptitle(f"Random{random_num}_rad{rad}_cost", fontsize=40)
        g.figure.subplots_adjust(top=0.95)

        for i, col in enumerate(columns):
            label = re.sub(f"Random{random_num}_rad{rad}_", "", col).replace("_cost", "")
            g.axes[i, 0].set_ylabel(label, fontsize=14)
            g.axes[-1, i].set_xlabel(label, fontsize=14)

        plt.savefig(f"Result_graph/Random{random_num}_rad{rad}_cost.pdf", bbox_inches='tight')
        plt.close()

In [ ]:
for i in [1]:
    for random_num in range(2,5):
        for rad in [0.5, 0.75]:
            data_frame_co = {}
            data_frame_st = {}
            data_frame_cost = {}
            # if rad == 0.5 and random_num == 3:
            #     pass
            # else:
            path = f"Random{random_num}_rad{rad}_to{i}.pkl"
            with open(path, "rb") as f:
                data = pickle.load(f)
            print("==========================")
            print(f"Random{random_num}_rad{rad}", data.shape)
            # data.info()
            # pg = sns.pairplot(data)
            for mesh in [50*i for i in range(1,8)]:
                mesh_data = data[f'{mesh}']

                data_co = mesh_data.apply(lambda x:x["compliance"].item())
                data_st = mesh_data.apply(lambda x:x["stress"].item())
                data_cost = mesh_data.apply(lambda x:x["cost"])

                mean_co = data_co.mean()
                mean_st = data_st.mean()
                mean_cost = data_cost.mean()

                std_co = data_co.std()
                std_st = data_st.std()
                std_cost = data_cost.std()
                
                data_frame_co[f"mesh{mesh}_compliance"] = -data_co
                data_frame_st[f"mesh{mesh}_stress"] = -data_st
                data_frame_cost[f"mesh{mesh}_cost"] = data_cost
        

                print("----------------------------")
                print("data_num=", len(mesh_data))
                print(f"Mesh: {mesh}")
                print(f"Mean Compliance: {-mean_co:.4f} ± {std_co:.4f}")
                print(f"Mean Stress: {-mean_st:.4f} ± {std_st:.4f}")
                print(f"Mean Cost: {mean_cost:.4f} ± {std_cost:.4f}")



            

In [ ]:
path = "Random2_rad0.75_to1.pkl"

with open(path, "rb") as f:
    data = pickle.load(f)

# 1. 行数・列数などの情報
print("shape=",data.shape)  # 例: (100, 5)

# 2. 各列の型と欠損値の有無
print("info=",data.info())

# 3. 先頭の数行を表示（デフォルト5行）
print("head=",data.head())

# 4. 統計量の要約（数値列のみ）
print("describe=",data.describe())

# 5. 列名一覧
print("col_name",data.columns)


shape= (192, 8)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 192 entries, 0 to 191
Data columns (total 8 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   x       192 non-null    object
 1   50      192 non-null    object
 2   100     192 non-null    object
 3   150     192 non-null    object
 4   200     192 non-null    object
 5   250     192 non-null    object
 6   300     192 non-null    object
 7   350     192 non-null    object
dtypes: object(8)
memory usage: 12.1+ KB
info= None
head=                                                    x  \
0  [0.04637589727836735, 0.07991580592461987, 0.0...   
1  [0.004203126954769463, 0.04193179954421694, 0....   
2  [0.09863563400183542, 0.025931507199719428, 0....   
3  [0.08945728762254004, 0.019823438289053766, 0....   
4  [0.05313004326654707, 0.015049335238371611, 0....   

                                                  50  \
0  {'compliance': [[-0.0300227]], 'stress': [[-0....   
1  {'complian

/home/ueda.shuji/miniconda3/envs/MFconda2/lib/python3.9/site-packages/pandas/core/indexes/base.py:5360: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  return key in self._engine


In [ ]:
for i in range(1, 8):
    x_c = data['x'].apply(lambda x: x[i])
    # print("x_c=")
    # print(x_c.mean())
    # print(x_c.var())
    x_c_scaled = x_c / 0.1
    print("x_c_scaled=")
    print(x_c_scaled.mean())
    print(x_c_scaled.var())

x_c_scaled=
0.5089450423504318
0.09389956050572741
x_c_scaled=
0.5030344248310774
0.09158060741535282
x_c_scaled=
0.501910827907527
0.08740597557292377
x_c_scaled=
0.4969562443239743
0.08728594224269282
x_c_scaled=
0.4928660863406618
0.0901579081100328
x_c_scaled=
0.5114102551746942
0.08972673013693629
x_c_scaled=
0.49968888804934153
0.09170187478727823


In [ ]:
print(data.shape)
print(data.columns)
print(data.x.shape)
print(data.x[0])
print(data.x[0].shape)

(15, 3)
Index(['x', 'mesh5', 'mesh6'], dtype='object')
(15,)
[0.01040487 0.07033419 0.00509365 0.08226648 0.05514044 0.06895538
 0.06369201 0.03662676]
(8,)


In [ ]:
print(data.shape)
print(data.columns)
print(data.mesh5.shape)
print(data.mesh5[0])
print(data.mesh5[0]['stress'])
print(data.mesh5[0]['cost'])


(15, 3)
Index(['x', 'mesh5', 'mesh6'], dtype='object')
(15,)
{'compliance': array([[-0.01071]]), 'stress': array([[-0.0629364]]), 'cost': 7.58073}
[[-0.0629364]]
7.58073


In [ ]:
with open("/home/ueda.shuji/myexp/Modules/initial_sampling/Random3_rad0.75_to2.pkl", "rb") as f:
    data_sparce = pickle.load(f)
# print(data)

compliance = data_sparce["50"].apply(lambda x: x["compliance"].item())
x_sparce = data_sparce['x'].apply(lambda x: x)
x_sparce = np.vstack(x_sparce)

print(x_sparce)
print()

with open("/home/ueda.shuji/myexp/Modules/initial_sampling/Random2_rad0.75_to2.pkl", "rb") as f:
    data_ful = pickle.load(f)
# print(data)

compliance = data_ful["50"].apply(lambda x: x["compliance"].item())
x_ful = data_ful['x'].apply(lambda x: x)
x_ful = np.vstack(x_ful)

print(x_ful)
print()



# 結果を格納するリスト
indices = []

for row in x_sparce:
    # Bのどの行と一致するかを探す
    matches = np.where((x_ful == row).all(axis=1))[0]
    if len(matches) > 0:
        indices.append(matches[0])  # 最初の一致だけ使う場合
    else:
        indices.append(-1)  # 一致しない場合

print(indices)


[[0.02589267 0.03093795 0.05858875 ... 0.06940071 0.05079791 0.06457274]
 [0.0305348  0.03220026 0.07303993 ... 0.08651996 0.03307488 0.05227275]
 [0.01823333 0.09660325 0.03568614 ... 0.00535548 0.08277782 0.06959257]
 ...
 [0.05888852 0.08951994 0.04772985 ... 0.01011937 0.0377168  0.0799371 ]
 [0.09102691 0.05182841 0.0776285  ... 0.0394142  0.02539678 0.00436985]
 [0.06033184 0.00501983 0.05848835 ... 0.08638797 0.00394106 0.02815152]]

[[0.04100381 0.066942   0.0599471  ... 0.026324   0.00532105 0.07629076]
 [0.02364936 0.00188246 0.09564709 ... 0.08026603 0.0700786  0.04398044]
 [0.03816768 0.07806689 0.07488856 ... 0.02328921 0.04419255 0.02443976]
 ...
 [0.02163263 0.01046461 0.02177417 ... 0.09137483 0.09448997 0.00465122]
 [0.07752699 0.01984387 0.03893052 ... 0.07653331 0.00744098 0.04059442]
 [0.03265439 0.01588934 0.02999504 ... 0.05432387 0.04915521 0.01123832]]

[27, 68, 79, 22, 88, 45, 82, 63, 61, 62, 11, 83, 72, 54, 36, 3, 30, 78, 31, 50, 7, 53, 17, 25, 70, 33, 86, 77,